apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiVmVyb25pa2FTaGV2Y2h1ayIsInBhc3N3b3JkIjoiZ2hwXzZVVkxEQk9TV3hzVG0yTENNSHhCSkowZURMSDhGczJwV2hZaSIsImVtYWlsIjoibmlrYV9zaHVAbWFpbC5ydSIsImF1dGgiOiJWbVZ5YjI1cGEyRlRhR1YyWTJoMWF6cG5hSEJmTmxWV1RFUkNUMU5YZUhOVWJUSk1RMDFJZUVKS1NqQmxSRXhJT0Vaek1uQlhhRmxwIn19fQ==
type: kubernetes.io/dockerconfigjson
