apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: cinemaabyss
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cinemaabyss.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy-service
            port:
              number: 8000
      - path: /api/monolith
        pathType: Prefix
        backend:
          service:
            name: monolith-service
            port:
              number: 8080
      - path: /api/movies
        pathType: Prefix
        backend:
          service:
            name: movies-service
            port:
              number: 8081
      - path: /api/events
        pathType: Prefix
        backend:
          service:
            name: events-service
            port:
              number: 8082