@startuml Контекстная диаграмма системы "Тёплый дом"
!include architecture-warmhouse\diagrams\templates\C4_Context.puml

title Контекстная диаграмма монолитного приложения "Тёплый дом"

Person(пользователь, "Пользователь", "Управляет отоплением и просматривает температуру через веб-интерфейс")
System(монолит, "Монолит 'Тёплый дом'", "Управление отоплением и сбор телеметрии")
System(датчик, "Датчик температуры", "Отправляет данные о температуре в доме")

Rel(пользователь, монолит, "HTTP-запросы", "REST API")
Rel(монолит, датчик, "Синхронные запросы", "HTTP/CoAP")
@enduml